import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

// don't think that this library has type declarations yet
// @ts-ignore 
import Faq from "react-faq-component";

import { Navbar } from '../components/Navbar'
import { Footer } from '../components/Footer'

import { Header } from '../components/Header'
import { Email } from '../components/Email'

const data = {
  title: "FAQ",
  rows: [
      {
          title: "How does moonfi work?",
          content: `We convert your deposits on moonfi into USDC, a fully-collateralized stablecoin pegged to the value of the US dollar backed by crypto giants Coinbase and Circle. This yield is generated by putting USDC into high-yield decentralized finance protocols, like AAVE and Uniswap, which generate the yield for our users!`,
      },
      {
          title: "Are my moonfi deposits stable?",
          content:
              "All holdings are converted to USDC, which is always redeemable for 1 US dollar. This makes USDC a relatively secure asset because it has tangible, redeemable value!",
      },
      {
          title: "How are the yields generated?",
          content: "We generate yield through decentralized finance protocols which have a higher yield than traditional finance due to high demand for USDC and the lack of a middleman taking large cuts of your interest."
      },
  ],
};


const styles = {
  // bgColor: 'white',
  titleTextColor: "#6988f4",
  rowTitleColor: "#6988f4",
  // rowContentColor: 'grey',
  // arrowColor: "red",
};

const config = {
  // animate: true,
  // arrowIcon: "V",
  // tabFocus: true
};

const About: NextPage = () => {
  return (
    <div className="bg-white min-h-screen flex flex-col">
      <Head>
        <title>{process.env.companyName}</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen min-h-screen flex flex-col">
        <Navbar showSlogan={false} />
        <div className="grow flex flex-col justify-center items-center lg:px-36 px-12 pb-5">
          <Header />
          <div className="flex md:flex-row flex-col justify-between justify-items-stretch lg:mb-10 md:mb-8 mb-2 mt-5">
            <Faq
              data={data}
              styles={styles}
              config={config}
            />
          </div>            
        </div>
        <Footer/>
      </main>
    </div>
  )
}

export default About
