name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  companyName: 'moonfi'
  AIRTABLE_API_KEY: 'keyFAXO0VtU5TJJps'
  AIRTABLE_BASE_KEY: 'appF4MHAqJKvrjSw7'
  DISCORD_INVITE: 'https://discord.gg/AY85vWmgev'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_PATH: /moonfi

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run export
      - run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out
